# Generated by Django 5.0.2 on 2024-02-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCar', models.CharField(max_length=255)),
                ('content', models.TextField(default='')),
                ('price', models.PositiveSmallIntegerField(default=1)),
                ('year', models.PositiveSmallIntegerField(default=1000)),
                ('imgCar', models.ImageField(upload_to='mediaCar', blank=True, null=True)),
            ],
        ),
    ]
