# Generated by Django 5.0.3 on 2024-03-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalonSamochodowy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='listCars',
            new_name='CarList',
        ),
    ]

